spring:
  application:
    name: inventory-service
  config:
    import: configserver:http://localhost:8888

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: refresh, health
